### ISSUE TITLE
Add Pull to refresh in Wallet screen

### ISSUE THREAD

**Issue by aguycalled** [aguycalled/WhisperWallet#14]
Pulling to refresh would call `Sync()` on `WalletFile`

**Comment by tsejerome** [comment]
shd I call this function for triggering Sync()?: 
`if (njs && win) njs.wallet.WalletFile.ListWallets().then(setWalletsList);

**Comment by tsejerome** [comment]
Plan:
Create a function from WalletProvider called RefreshWallet
```
const refreshWallet = async() => {
  if (!njs || !win) return; 
  await njs.wallet.WalletFile.Sync();
  await njs.wallet.WalletFile.ListWallets().then(setWalletsList);
}
```

**Comment by aguycalled** [comment]
Sync is not a static member so it should be called on the WalletFile object. ListWallets is not needed.

**Comment by tsejerome** [comment]
>Sync is not a static member so it should be called on the WalletFile object. 
do you mean `wallet.sync()` is good enough?

**Comment by aguycalled** [comment]
yes

**Comment by aguycalled** [comment]
Sync should also be called if there is a wallet open and the app comes to foreground from background, but that can maybe be a different task

**Comment by tsejerome** [comment]
Sure, will add to new issue
