### ISSUE TITLE
Fix Layout for different device screens

### ISSUE THREAD

**Issue by aguycalled** [aguycalled/WhisperWallet#15]
For example, Onboarding screen looks broken on iPad.

**Comment by tsejerome** [comment]
We shd set our layout to dynamically adjust. There are some react native packages for handling that, will do that later on.

Overall, we shd have a list of preferred devices for testing too, with rationale as mentioned at #15. Especially when we handle issues like #17 and #15

**Comment by tsejerome** [comment]
|Screens   |iPhone 8   | iPhone 12 Pro Max  |  iPad Air |iPad Pro   |Pixel 2 | Pixel 5
|---|---|---|---|---|---|---|
|AddressScreen   |   |   |   |   | |   |
|AddServerScreen   |   |   |   |   | |   |
|HistoryScreen   |   |   |   |   | |   |
|MainWalletScreen   |   |   |   |   | |   |
|MenmonicScreen   |   |   |   |   | |   |
|SendToScreen   |   |   |   |   | |   |
|AddServerScreenViewTXScreen   |   |   |   |   | |   |
|OnboardingScreen   |   |   |   |   | |   |


@aguycalled Thoughts on this flow? Any screens I'm missing?

**Comment by aguycalled** [comment]
I think `AddServerScreenViewTXScreen` has a typo and refers to two different screens.

I would also add the Screens under `navigation/`: `CreateNewWallet`, `ImportWallet` and `OpenWallet`.
