### ISSUE TITLE
Check react-native-keychain implementation

### ISSUE THREAD

**Issue by aguycalled** [aguycalled/WhisperWallet#17]
Doing some tests in a real iOS device, I realised it is not checking my biometrics (Face ID) anymore when opening a wallet or sending a transaction.

Need to verify implementation is correct in all cases (Face ID not available, Touch ID, etc.).

Haven't had the chance to test this in Android.

**Comment by tsejerome** [comment]
Overall, we shd have a list of preferred devices for testing too, with rationale.

**Things to test:**
Native Modules like Face ID
UI Layout

**Proposal:**
iPhone X (Notch + Face ID, UI releavant)
iPhone 7/8 (Without Notch, Without Face ID + older device)
Pixel 6 (In Screen Touch Unlock, no face unlock + it's my usual phone lol)
Pixel 3 (Separated Hardware Touch Unlock, no face unlock + it's my old phone lol, shd be no diff with pixel 6 but need to cross check)
One Android Phone with face id (open for sugestions)

**Comment by aguycalled** [comment]
agreed, I think we should also include tablets on both archs
