### ISSUE TITLE
Android crashes on simulator

### ISSUE THREAD

**Issue by aguycalled** [aguycalled/WhisperWallet#2]
`npx react-native run-android` crashes:

<img width="532" alt="Screenshot 2022-03-15 at 19 26 47" src="https://user-images.githubusercontent.com/24814046/158446553-6bedaf14-c1bd-4567-ade3-f183c1b164e1.png">

Could not find references of this crash online. Might be related to some of the libraries used in the module. Haven't tested on a real device.

**Comment by tsejerome** [comment]
![image](https://user-images.githubusercontent.com/20391660/159613322-87698ddc-4780-46bd-af14-9bf6bb2a382f.png)
As per discussed, @aguycalled discovered that it is relevant to the package `@aguycalled/noble-bls12-381` which is used in `navcoin-js`, `@aguycalled/bitcore-p2p` & `@aguycalled/bitcore-lib`

@aguycalled will take over the task

**Comment by aguycalled** [comment]
Once https://github.com/herumi/mcl/issues/138 is solved, we will be able to use `react-native-mcl` for signing so we can discard completely `noble` and this issue should be gone.

**Comment by aguycalled** [comment]
fixed
