### ISSUE TITLE
Transaction List missing placeholder

### ISSUE THREAD

**Issue by aguycalled** [aguycalled/WhisperWallet#28]
When a Transaction History list is empty, it shows nothing but it should show some placeholder.

**Comment by tsejerome** [comment]
Choice of text:

```

export enum Connection_Stats_Text {
  Connecting = 'Connecting to wallet...',
  ConnectedButEmpty = 'There are no transaction record yet!',
  Syncing = 'Synchronizing wallet...',
  Disconnected = 'Wallet is disconnected.',
  NoServers = 'No servers found! Please contact our administrator through discord.',
}
```

**Comment by tsejerome** [comment]
UI Updates:
![image](https://user-images.githubusercontent.com/20391660/160795697-1edcbbff-bb6b-440e-bffa-da835f6afcd9.png)

![image](https://user-images.githubusercontent.com/20391660/160792463-ba3d10ea-912a-4ae2-87ce-010fbfe7a47d.png)

**Comment by tsejerome** [comment]
Sure, let's remove start a transaction. (There might be a case where staking doesn't have $$ but private wallet does have though. It might be a future enhancement.)

**Comment by tsejerome** [comment]
Updated 👯‍♂️
