### ISSUE TITLE
react-native-mcl polyfill needs manual intervention

### ISSUE THREAD

**Issue by aguycalled** [aguycalled/WhisperWallet#3]
`react-native-mcl` is a polyfill for `@aguycalled/mcl-wasm`, which is used by `@aguycalled/bitcore-lib`.

When doing `npm i`, there exist two copies of the module one in `node_modules` and the second in `node_modules/@aguycalled/bitcore-lib/node_modules`.

Seems like `pod install` setups the one in `node_modules` but `@aguycalled/bitcore-lib` loads the one in `node_modules/@aguycalled/bitcore-lib/node_modules`, making the app crash on the iOS simulator, requiring to manually delete the folder `node_modules/@aguycalled/bitcore-lib/node_modules` to be able to launch the app.

This is not critical, but would be nice if it can get fixed, maybe adding a post install rule in `package.json`.

**Comment by aguycalled** [comment]
fixed

**Comment by tsejerome** [comment]
Next time cud mention the commit / PR number, easier for future referencing
