### ISSUE TITLE
Swipe to Confirm aesthetics

### ISSUE THREAD

**Issue by aguycalled** [aguycalled/WhisperWallet#6]
The `Swipe to Confirm` button's background needs to have the top and bottom left corners rounded.

<img width="309" alt="image" src="https://user-images.githubusercontent.com/24814046/158447799-21d2b38f-4e58-426f-bbce-c2d3f96cbc6d.png">

**Comment by tsejerome** [comment]
![image](https://user-images.githubusercontent.com/20391660/159634621-d64628ca-cfc5-4a7c-af46-02349c305930.png)

![image](https://user-images.githubusercontent.com/20391660/159634565-00392e9a-5750-4b5b-9e58-59b79563cbb1.png)

Issue: 
Image 1: left side radius is not happening
Image 2: the `SwipeButtonText_1` is commented and the border radius is here
