### ISSUE TITLE
Trying to move NAV to xNAV gives an error

### ISSUE THREAD

**Issue by willoncio-nav** [aguycalled/WhisperWallet#69]
It took longer than expected to see the balance on the screen below, around 4-5 minutes, which I expected sooner as the transaction should be confirmed.

When moving to xNAV having the balance now visible, I get the error below
![IMG_1240](https://user-images.githubusercontent.com/97851131/163562085-9e736b63-11c9-4d85-97e2-3932ec587cdf.PNG)

**Comment by aguycalled** [comment]
what is your iOS version and iPhone model?

**Comment by willoncio-nav** [comment]
iOS: 15.3.1
iPhone XR

Same behaviour when trying to move to NavCash Pool Staking

**Comment by aguycalled** [comment]
fixed in f59ecb0693afc74b57e12dc785c32d9d212a711b will push to testflight

**Comment by willoncio-nav** [comment]
All types of transactions working fine now
